[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ual"
version = "0.18.0"
description = "Utilities shared across UrbanAirLab projects"
readme = "README.md"
authors = [
  { name = "UrbanAirLab", email = "Marc.Golder@hs-heilbronn.de" },
]
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.2.3",
    "influxdb-client>=1.50.0",
    "isort>=9.0.1",
    "mypy>=2.3.1",
    "numpy>=2.5.3",
    "paho-mqtt>=2.1.0",
    "pandas>=3.0.5",
    "pip-audit>=2.10.1",
    "pytest>=9.1.1",
    "pyyaml>=6.0.3",
    "ruff>=0.16.7",
    "scipy>=1.18.1",
]
